server:
  port: 10001

#jwt:
#  time: 30000
#  value: userserviceuserserviceserserviceuserserviceuserserviceserservice
#  name: "X-TOKEN"
spring:
  application:
    name: user-service
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3307/msaProject?useUnicode=true&characterEncoding=utf-8
    username: kk
    password: 1234
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    generate-ddl: true
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  profiles:
    active: dev

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.value}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka


logging:
  level:
    com.example.user: debug

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, busrefresh